config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "home#top"
  resources :users, only:[:show, :edit, :update, :destroy]

  resources :shops do
    resources :comments, only:[:create, :destroy]
    member do
      get :liking_users
    end
    collection do
      match 'search' => 'shops#search', via: [:get, :post], as: :search
    end
  end
  resources :tags, only: [:index, :show]
  post "/like/:shop_id" => "likes#like", as: "like"
  delete "/unlike/:shop_id" => "likes#unlike", as: "unlike"
  get "/contact" => "contacts#new", as: "contact"
  post "/contact" => "contacts#create"
  get "/published" => "home#published"

end

app/models/shop.rb
require 'file_size_validator'
class Shop < ActiveRecord::Base
  # 店舗画像アップロード
  mount_uploader :shop_image, ShopImageUploader
  # バリデーション
  validates :shop_name, presence: true
  validates :shop_bio, length: {maximum: 300}
  validates :location, presence: true
  validates :user_id, presence: true
  # 投稿の際の画像のサイズをバリデーション
  validates :shop_image, file_size: {maximum: 5.megabytes.to_i} # 最大5MBに制限
  # アソシエーション
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  belongs_to :area
  # google map
  geocoded_by :location
  after_validation :geocode, :if => :location_changed?
  # タグ
  acts_as_taggable_on :tags
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  # ログイン必須
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # ビフォーアクション
  before_action :set_shop, only: [:show, :edit, :update, :destroy, :correct_user, :liking_users]
  # ログイン中のユーザーのビフォーアクション
  # before_action :correct_user, only:[:edit, :update]
  # 管理者オンリー
  before_action :authorize_admin, only:[:new, :create, :edit, :update, :destroy]
  # 店舗一覧
  def index
    @q = Shop.ransack(params[:q])
    @shops = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(12)
  end
  # 店舗詳細
  def show
    @hash = Gmaps4rails.build_markers(@shop) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
    end
    @comment = Comment.new
    @comments = @shop.comments.order(created_at: :desc).page(params[:page]).per(10)
  end
  # 店舗投稿
  def new
    @shop = Shop.new
  end
  # 店舗投稿
  def create
    @shop = current_user.shops.build(shop_params)
    if @shop.save
      flash[:success] = "投稿しました！"
      redirect_to @shop
    else
      render :new
    end
  end
  # 店舗編集
  def edit
    #code
  end
  # 店舗編集
  def update
    if @shop.update(shop_params)
      flash[:success] = "編集しました。"
      redirect_to @shop
    else
      render :edit
    end
  end
  # 店舗削除
  def destroy
    @shop.destroy
    flash[:success] = "投稿を削除しました。"
    redirect_to root_path
  end
  # 店舗にいいね!しているユーザー
  def liking_users
    @users = @shop.liking_users.order(created_at: :desc).page(params[:page]).per(10)
    @title = "いいね！したユーザー"
  end
  # 検索
  def search
    index
    render :index
  end


  private
  # セット
  def set_shop
    @shop = Shop.find(params[:id])
  end
  # ストロングパラメーター
  def shop_params
    params.require(:shop).permit(:shop_name, :shop_bio, :tel, :location, :latitude, :longitude, :hours, :closed, :shop_image, :shop_image_cache, :url, :user_id, :area_id, :tag_list)
  end
  # 正しいユーザーか
  # def correct_user
    # unless current_user?(@shop.user)
      # redirect_to root_path
    # end
  # end
  # 管理者かどうか
  def authorize_admin
    unless current_user.admin?
      redirect_to root_path
    end
  end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop, html: {multipart: true}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%# 画像の投稿部分。もしバリデーションに引っかかった場合、画像を表示しておく。 %>
  <div class="form-group">
    <%= image_tag @shop.shop_image.url(:thumb) if @shop.shop_image? %>
    <%= f.label :shop_image %><br>
    <%= f.file_field :shop_image, class: "form-control" %>
    <%= f.hidden_field :shop_image_cache %>
  </div>
  <div class="form-group">
    <%= f.label :shop_name %>(必須)<br>
    <%= f.text_field :shop_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :shop_bio %>(200文字以内)<br>
    <%= f.text_area :shop_bio, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tel %><br>
    <%= f.text_field :tel, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :hours %><br>
    <%= f.text_field :hours, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :closed %><br>
    <%= f.text_field :closed, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :area %>
    <%= f.collection_select :area_id, Area.all, "id", "name", {prompt: "エリアを選択"}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list, value: f.object.tag_list.to_s, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "投稿する", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shops/_search.html.erb
<%= search_form_for @q, url: search_shops_path, html: {method: :post} do |f| %>
<div class="form-group">
  <h4 class="search-label">店舗名から探す</h4>
  <%= f.search_field :shop_name_cont, placeholder: "店舗名", class: "form-control" %>
</div>
<div class="form-group">
  <h4 class="search-label">所在地から探す</h4>
  <%= f.search_field :location_cont, placeholder: "都道府県または市区町村", class: "form-control" %>
</div>
<div class="form-group">
  <h4 class="search-label">人気のエリアから探す</h4>
  <%= f.collection_select :area_id_eq, Area.all, "id", "name", {prompt: "エリアを選択"}, {class: "form-control"} %>
</div>
<div class="actions">
  <%= f.submit "検索", class: "btn btn-primary btn-block" %>
</div>
<% end %>

app/views/shops/_shop.html.erb
<!-- 店舗パーシャル  -->
<div class="col-xs-6 col-sm-4 col-md-4">
  <%= link_to shop do %>
  <div class="thumbnail">
    <div class="thumb">
      <% if shop.shop_image? %>
      <%= image_tag(shop.shop_image.url) %>
      <% else %>
      <%= image_tag "default-shop-image.png" %>
      <% end %>
    </div>
    <div class="caption">
      <p><strong><%= truncate(shop.shop_name, length: 10) %></strong></p>
      <p class="card-bottom"><i class="fa fa-heart-o"><%= shop.likes.count %></i> | <i class="fa fa-comment-o"><%= shop.comments.count %></i></p>
    </div>
  </div>
  <% end %>
</div>

app/views/shops/edit.html.erb
<% @page_title = "投稿編集" %>

<div class="gray-color">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="form-wrapper">
          <h2>店舗編集</h2>
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<% @page_title = "店舗検索" %>

<div class="container">
  <div class="row">
    <!-- 検索フォーム -->
    <div class="col-md-4">
      <div class="search-wrapper">
        <div class="page-header">
          <h1>店舗検索</h1>
        </div>
        <%= render "search" %>
      </div>
      <%= render "shared/auto_ad" %>
    </div>
    <!-- 店舗一覧 -->
    <div class="col-md-8">
      <div class="shops-wrapper">
        <div class="page-header">
          <h1>店舗一覧</h1>
        </div>
        <div class="row">
          <%= render @shops %>
        </div>
        <div class="pagination pagination-centered">
          <%= paginate @shops %>
        </div>
        <%= render "shared/auto_ad" %>
      </div>
    </div>
  </div>
</div>

app/views/shops/liking_users.html.erb
<% @page_title = "いいね！したユーザー" %>

<div class="gray-color">
  <div class="container">
    <div class="row">
      <%# 店舗一覧 %>
      <div class="col-md-8 col-md-offset-2">
        <div class="liking-users">
          <div class="page-header">
            <h1><%= @title %></h1>
          </div>
          <ul class="lists">
            <%= render @users %>
          </ul>
          <div class="pagination pagination-centered">
            <%= paginate @users %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shops/new.html.erb
<% @page_title = "新規投稿" %>

<div class="gray-color">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="form-wrapper">
          <h2>店舗投稿</h2>
          <%= render "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shops/show.html.erb
<% @page_title = @shop.shop_name %>

<div class="container">
  <!-- コンテンツ上側 -->
  <div class="row">
    <!-- コンテンツ左側 -->
    <div class="col-md-8">
      <!-- 店舗情報の大枠 -->
      <div class="shop-wrapper">
        <!-- アドセンス -->
        <%= render "shared/horizontal_ad" %>
        <!-- 警告文 -->
        <div class="alert alert-warning">
          <small>情報が古い場合があり、必ずしも正しいとは限りません。( <%= @shop.updated_at.strftime("%Y/%m/%d") %>に更新 )</small>
        </div>
        <!-- 店舗名 -->
        <h1 class="shop-name-heading"><%= @shop.shop_name %></h1>
        <div class="shop-tags">
          <%= render @shop.tags %>
        </div>
        <!-- 管理ユーザーがログイン済みの時のメニュー -->
        <% if current_user.try(:admin?) %>
        <ul>
          <li><%= link_to "編集", edit_shop_path(@shop.id) %></li>
          <li><%= link_to "削除", shop_path(@shop.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></li>
        </ul>
        <% end %>
        <!-- 店舗イメージ -->
        <div class="shop-image">
          <% if @shop.shop_image? %>
          <%= image_tag(@shop.shop_image.url) %>
          <% else %>
          <%= image_tag "default-shop-image.png" %>
          <% end %>
        </div>
        <!-- 店舗概要 -->
        <p class="shop-bio"><%= @shop.shop_bio %></p>
        <!-- 店舗テーブル -->
        <div class="table-responsive">
          <table class="table table-bordered table-condensed">
            <tbody>
              <tr>
                <th scope="row">電話</th>
                <td><%= @shop.tel %></td>
              </tr>
              <tr>
                <th scope="row">所在地</th>
                <td><%= @shop.location %></td>
              </tr>
              <tr>
                <th scope="row">営業時間</th>
                <td><%= @shop.hours %></td>
              </tr>
              <tr>
                <th scope="row">定休日</th>
                <td><%= @shop.closed %></td>
              </tr>
              <tr>
                <th scope="row">サイト</th>
                <td><%= link_to @shop.url, @shop.url, rel: "noopener", target: "_blank" %></td>
              </tr>
            </tbody>
          </table>
        </div>
        <!-- 店舗地図 -->
        <div class='shop-map'>
          <div id="map"></div>
          <script type="text/javascript">
              handler = Gmaps.build('Google');
              handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
                markers = handler.addMarkers(<%=raw @hash.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
                handler.getMap().setZoom(16);
              });
          </script>
        </div>
        <!-- アドセンス -->
        <%= render "shared/auto_ad" %>
      </div><!-- show-wrapper -->
    </div><!-- col-md-8 -->
    <!-- コンテンツ右側 -->
    <div class="col-md-4">
      <!-- サイドバーの大枠 -->
      <div class="sidebar">
        <!-- SNSシェアボタン -->
        <div class="well">
          <%= render "shared/sns" %>
        </div>
        <!-- いいね関連 -->
        <div class="like-info-wrapper">
          <div id="like-link">
            <%= render "likes/like_links", shop: @shop %>
          </div>
          <div class="like-count">
            <%= link_to @shop.likes.count, liking_users_shop_path(@shop.id), id: "like-count" %>いいね!
          </div>
        </div>
        <!-- 近くの店舗 -->
        <% if @shop.geocoded? %>
        <div class="nearbys">
          <h3>近くの店舗</h3>
          <ul>
            <% @shop.nearbys(1).limit(10).each do |shop| %>
            <li><%= link_to shop.shop_name, shop %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <!-- アドセンス -->
        <%= render "shared/rectangle_ad" %>
        <!-- あとで実装 -->
      </div><!-- sidebar -->
    </div><!-- col-md-4 -->
  </div><!-- コンテンツ上側 -->
  <!-- コンテンツ下側 -->
  <div class="row">
    <!-- コンテンツ下側左 -->
    <div class="col-md-8">
      <!-- コメント一覧の大枠 -->
      <div class="comments-wrapper">
        <!-- コメントしてるかどうか -->
        <% if user_signed_in? %>
        <% if current_user.comments.find_by(shop_id: @shop.id) %>
        <div class="alert alert-warning">
          <small>※あなたはこのお店にコメント済みです。</small>
        </div>
        <% end %>
        <% end %>
        <!-- コメント投稿フォーム -->
        <%= render "comments/form", shop: @shop %>
        <!-- コメント一覧 -->
        <ul class="shop-comments">
          <h4>コメント数(<%= @shop.comments.count %>)</h4>
          <% if @shop.comments.any? %>
          <ul class="lists">
            <%= render @comments %>
          </ul>
          <% else %>
          <%= "まだコメントがありません。" %>
          <% end %>
          <%= paginate @comments %>
        </ul>
      </div><!-- comments-wrapper -->
    </div><!-- コンテンツ下側左 -->
  </div><!-- コンテンツ下側 -->
</div>