config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "home#top"
  resources :users, only:[:show, :edit, :update, :destroy]

  resources :shops do
    resources :comments, only:[:create, :destroy]
    member do
      get :liking_users
    end
    collection do
      match 'search' => 'shops#search', via: [:get, :post], as: :search
    end
  end
  resources :tags, only: [:index, :show]
  post "/like/:shop_id" => "likes#like", as: "like"
  delete "/unlike/:shop_id" => "likes#unlike", as: "unlike"
  get "/contact" => "contacts#new", as: "contact"
  post "/contact" => "contacts#create"
  get "/published" => "home#published"

end

app/models/like.rb
class Like < ActiveRecord::Base
  # アソシエーション
  belongs_to :user
  belongs_to :shop
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  # いいねアクション
  def like
    @shop = Shop.find(params[:shop_id])
    like = current_user.likes.build(shop_id: @shop.id)
    like.save
  end
  # いいね取り消しアクション
  def unlike
    @shop = Shop.find(params[:shop_id])
    like = current_user.likes.find_by(shop_id: @shop.id)
    like.destroy
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like_links.html.erb
<% if user_signed_in? %>
  <% if current_user.likes.find_by(shop_id: shop.id) %>
    <%= link_to "いいね!を取り消す", unlike_path(shop.id), method: :delete, remote: true, class: "btn btn-unlike" %>
  <% else %>
    <%= link_to like_path(shop.id), method: :post, remote: true, class: "btn btn-like" do %>
      <i class="fa fa-heart"> いいね!をする </i>
    <% end %>
  <% end %>
<% end %>

app/views/likes/like.js.erb
$("#like-link").html("<%= escape_javascript(render("likes/like_links", shop: @shop)) %>");
$("#like-count").html("<%= @shop.likes.count %>");

app/views/likes/unlike.js.erb
$("#like-link").html("<%= escape_javascript(render("likes/like_links", shop: @shop)) %>");
$("#like-count").html("<%= @shop.likes.count %>");