config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "home#top"
  resources :users, only:[:show, :edit, :update, :destroy]

  resources :shops do
    resources :comments, only:[:create, :destroy]
    member do
      get :liking_users
    end
    collection do
      match 'search' => 'shops#search', via: [:get, :post], as: :search
    end
  end
  resources :tags, only: [:index, :show]
  post "/like/:shop_id" => "likes#like", as: "like"
  delete "/unlike/:shop_id" => "likes#unlike", as: "unlike"
  get "/contact" => "contacts#new", as: "contact"
  post "/contact" => "contacts#create"
  get "/published" => "home#published"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/area.rb
class Area < ActiveRecord::Base
  # アソシエーション
  has_many :shops
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # アソシエーション
  belongs_to :user
  belongs_to :shop
  # バリデーション
  validates :content, presence: true
end

app/models/contact.rb
class Contact

  include ActiveModel::Model

  attr_accessor :email, :message

  validates :email, :presence => {:message => 'メールを入力してください'}
  validates :message, :presence => {:message => 'メッセージを入力してください'}

end

app/models/like.rb
class Like < ActiveRecord::Base
  # アソシエーション
  belongs_to :user
  belongs_to :shop
end

app/models/shop.rb
require 'file_size_validator'
class Shop < ActiveRecord::Base
  # 店舗画像アップロード
  mount_uploader :shop_image, ShopImageUploader
  # バリデーション
  validates :shop_name, presence: true
  validates :shop_bio, length: {maximum: 300}
  validates :location, presence: true
  validates :user_id, presence: true
  # 投稿の際の画像のサイズをバリデーション
  validates :shop_image, file_size: {maximum: 5.megabytes.to_i} # 最大5MBに制限
  # アソシエーション
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  belongs_to :area
  # google map
  geocoded_by :location
  after_validation :geocode, :if => :location_changed?
  # タグ
  acts_as_taggable_on :tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable #:trackable, :validatable
  # ユーザー画像アップロード
  mount_uploader :user_image, UserImageUploader
  # バリデーション
  validates :user_name, presence: true
  # アソシエーション
  has_many :shops, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_shops, through: :likes, source: :shop
  has_many :comments, dependent: :destroy
  has_many :comment_shops, through: :comments, source: :shop

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #トップページ
  def top
    @q = Shop.ransack(params[:q])
    if user_signed_in?
      @shops = Shop.all.order(created_at: :desc).page(params[:page]).per(12)
    else
      @shops = Shop.all.order(created_at: :desc).limit(6)
    end
  end

  # 掲載説明
  def published
    #code
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  # いいねアクション
  def like
    @shop = Shop.find(params[:shop_id])
    like = current_user.likes.build(shop_id: @shop.id)
    like.save
  end
  # いいね取り消しアクション
  def unlike
    @shop = Shop.find(params[:shop_id])
    like = current_user.likes.find_by(shop_id: @shop.id)
    like.destroy
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  # ログイン必須
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # ビフォーアクション
  before_action :set_shop, only: [:show, :edit, :update, :destroy, :correct_user, :liking_users]
  # ログイン中のユーザーのビフォーアクション
  # before_action :correct_user, only:[:edit, :update]
  # 管理者オンリー
  before_action :authorize_admin, only:[:new, :create, :edit, :update, :destroy]
  # 店舗一覧
  def index
    @q = Shop.ransack(params[:q])
    @shops = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(12)
  end
  # 店舗詳細
  def show
    @hash = Gmaps4rails.build_markers(@shop) do |shop, marker|
      marker.lat shop.latitude
      marker.lng shop.longitude
    end
    @comment = Comment.new
    @comments = @shop.comments.order(created_at: :desc).page(params[:page]).per(10)
  end
  # 店舗投稿
  def new
    @shop = Shop.new
  end
  # 店舗投稿
  def create
    @shop = current_user.shops.build(shop_params)
    if @shop.save
      flash[:success] = "投稿しました！"
      redirect_to @shop
    else
      render :new
    end
  end
  # 店舗編集
  def edit
    #code
  end
  # 店舗編集
  def update
    if @shop.update(shop_params)
      flash[:success] = "編集しました。"
      redirect_to @shop
    else
      render :edit
    end
  end
  # 店舗削除
  def destroy
    @shop.destroy
    flash[:success] = "投稿を削除しました。"
    redirect_to root_path
  end
  # 店舗にいいね!しているユーザー
  def liking_users
    @users = @shop.liking_users.order(created_at: :desc).page(params[:page]).per(10)
    @title = "いいね！したユーザー"
  end
  # 検索
  def search
    index
    render :index
  end


  private
  # セット
  def set_shop
    @shop = Shop.find(params[:id])
  end
  # ストロングパラメーター
  def shop_params
    params.require(:shop).permit(:shop_name, :shop_bio, :tel, :location, :latitude, :longitude, :hours, :closed, :shop_image, :shop_image_cache, :url, :user_id, :area_id, :tag_list)
  end
  # 正しいユーザーか
  # def correct_user
    # unless current_user?(@shop.user)
      # redirect_to root_path
    # end
  # end
  # 管理者かどうか
  def authorize_admin
    unless current_user.admin?
      redirect_to root_path
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # タグ一覧
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end
  # タグに紐付いた店舗一覧
  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @shops = Shop.tagged_with(@tag.name).page(params[:page]).per(12)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページタイトル
  def page_title
    title = "古着屋情報サイトのRopaRopa(ロパロパ)"
    title = @page_title + " | " + title if @page_title
    title
  end
  # ログインしてれば編集できる
  def current_user?(user)
    current_user == user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="RopaRopa(ロパロパ)は古着屋の情報サイトです。あなたも気になる古着屋をチェックしたり口コミを書いてみませんか。">
  <meta name="keywords" content="RopaRopa, ロパロパ, 古着, 口コミ, 古着屋">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= page_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <script src="//maps.google.com/maps/api/js?key=AIzaSyD6UdSPh_5GIoXHxQz8RasUkEfhXaBud60"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
</head>
<body>
  <%# ここからヘッダー %>
  <%= render "shared/header" %>
  <%# フラッシュ %>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <button class="close" type="button" data-dismiss="alert">&times;</button>
      <%= value %>
    </div>
  <% end %>
  <%# コンテンツ %>
  <%= yield %>
  <%# ここからフッター %>
  <%= render "shared/footer" %>
</body>
</html>

app/views/shared/_auto_ad.html.erb
<!-- レスポンシブアドセンス -->
<div class="google-ad">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- ロパロパ -->
  <ins class="adsbygoogle"
  style="display:block"
  data-ad-client="ca-pub-7098906806947664"
  data-ad-slot="6593571635"
  data-ad-format="auto"></ins>
  <script>
  (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <h3><%= object.errors.count %>件のエラーがあります。</h3>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <!-- ここからサイトの説明 -->
      <div class="col-sm-4">
        <h4>このサイトについて</h4>
        <p>"RopaRopa" は古着屋の情報サイトで口コミができるサイトです。<br>
          あなたも気になる古着屋をチェックしたり口コミを書いてみませんか？：）
        </p>
      </div>
      <!-- ここからログインメニュー -->
      <div class="col-sm-2">
        <h4>メニュー</h4>
        <ul class="footer-links">
          <% if user_signed_in? %>
            <li><%= link_to "トップ", root_path %></li>
            <li><%= link_to "ユーザートップ", current_user %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "ログイン", new_user_session_path %></li>
            <li><%= link_to "ユーザー登録", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
      <!-- ここからヘルプリンク -->
      <div class="col-sm-2">
        <h4>ヘルプ</h4>
        <ul class="footer-links">
          <li><%= link_to "店舗掲載について", published_path %></li>
          <li><%= link_to "コンタクト", contact_path %></li>
        </ul>
      </div>
      <!-- snsリンク -->
      <div class="col-sm-2">
        <h4>SNS</h4>
        <ul class="footer-links">
          <li><%= link_to "Twitter", "https://twitter.com/roparopacom", rel: "noopener", target: "_blank" %></li>
        </ul>
      </div>
    </div>
    <!-- コピーライト -->
    <small class="copyright">Copyright &copy; RopaRopa</small>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RopaRopa", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- ヘッダー左側 -->
      <ul class="nav navbar-nav">
        <!-- ユーザーがログイン済みの時のメニュー -->
        <% if current_user.try(:admin?) %>
          <li><%= link_to "投稿", new_shop_path %></li>
        <% end %>
        <!-- 検索ボックス -->
        <li>
          <%= link_to search_shops_path do %>
          <i class="fa fa-search" aria-hidden="true"></i>
          店舗検索
          <% end %>
        </li>
        <!-- PR部分 -->
        <li>
          <%= link_to published_path do %>
          <span class="header-pr">PR</span>
          <span>あなたのお店を掲載しませんか? ：）</span>
          <% end %>
        </li>
      </ul>
      <!-- ヘッダー右側 -->
      <ul class="nav navbar-nav navbar-right">
        <!-- ユーザーがログイン済みの時のメニュー -->
        <% if user_signed_in? %>
          <li><%= link_to current_user.user_name, current_user %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">設定<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "アカウント編集", edit_user_registration_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <li><%= link_to "ユーザー登録", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/shared/_horizontal_ad.html.erb
<!-- 横長アドセンス -->
<div class="google-ad">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- ロパロパ -->
  <ins class="adsbygoogle"
  style="display:block"
  data-ad-client="ca-pub-7098906806947664"
  data-ad-slot="6593571635"
  data-ad-format="horizontal"></ins>
  <script>
  (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

app/views/shared/_rectangle_ad.html.erb
<!-- レクタングルアドセンス -->
<div class="google-ad">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- ロパロパ -->
  <ins class="adsbygoogle"
  style="display:block"
  data-ad-client="ca-pub-7098906806947664"
  data-ad-slot="6593571635"
  data-ad-format="rectangle"></ins>
  <script>
  (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

app/views/shared/_sns.html.erb
<!-- SNSシェアボタン -->
<ul class="sns-share-buttons">
  <!-- Twitterボタン -->
  <li>
    <a href="https://twitter.com/share" class="twitter-share-button" data-via="roparopacom" data-hashtags="古着屋">Tweet</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
  </li>
  <!-- Facebookボタン -->
  <li>
    <iframe src="https://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fropa-ropa.com%2F&width=130&layout=button_count&action=like&size=small&show_faces=false&share=true&height=46&appId" width="130" height="20" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
  </li>
  <!-- Hatenaボタン -->
  <li>
    <a href="http://b.hatena.ne.jp/entry/" class="hatena-bookmark-button" data-hatena-bookmark-layout="basic-label-counter" data-hatena-bookmark-lang="ja" title="このエントリーをはてなブックマークに追加"><img src="https://b.st-hatena.com/images/entry-button/button-only@2x.png" alt="このエントリーをはてなブックマークに追加" width="20" height="20" style="border: none;" /></a>
    <script type="text/javascript" src="https://b.st-hatena.com/js/bookmark_button.js" charset="utf-8" async="async"></script>
  </li>
  <!-- Pocketボタン -->
  <li>
    <a data-pocket-label="pocket" data-pocket-count="horizontal" class="pocket-btn" data-lang="en"></a>
    <script type="text/javascript">!function(d,i){if(!d.getElementById(i)){var j=d.createElement("script");j.id=i;j.src="https://widgets.getpocket.com/v1/j/btn.js?v=1";var w=d.getElementById(i);d.body.appendChild(j);}}(document,"pocket-btn-js");</script>
  </li>
</ul>

app/views/shared/_user_info.html.erb
<!-- ユーザー情報パーシャル -->
<section>
  <div class="user-show-image">
    <% if current_user.user_image? %>
      <%= image_tag(current_user.user_image.url) %>
    <% else %>
      <%= image_tag "default-image.png" %>
    <% end %>
  </div>
</section>
<section>
  <span class="user-label">ユーザー名</span>
  <h3><%= current_user.user_name %></h3>
</section>