config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "home#top"
  resources :users, only:[:show, :edit, :update, :destroy]

  resources :shops do
    resources :comments, only:[:create, :destroy]
    member do
      get :liking_users
    end
    collection do
      match 'search' => 'shops#search', via: [:get, :post], as: :search
    end
  end
  resources :tags, only: [:index, :show]
  post "/like/:shop_id" => "likes#like", as: "like"
  delete "/unlike/:shop_id" => "likes#unlike", as: "unlike"
  get "/contact" => "contacts#new", as: "contact"
  post "/contact" => "contacts#create"
  get "/published" => "home#published"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #トップページ
  def top
    @q = Shop.ransack(params[:q])
    if user_signed_in?
      @shops = Shop.all.order(created_at: :desc).page(params[:page]).per(12)
    else
      @shops = Shop.all.order(created_at: :desc).limit(6)
    end
  end

  # 掲載説明
  def published
    #code
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_sign_in.html.erb
<div class="container">
  <div class="row">
    <!-- 検索フォーム -->
    <div class="col-md-4">
      <div class="search-wrapper">
        <div class="page-header">
          <h1>店舗検索</h1>
        </div>
        <%= render "shops/search" %>
      </div>
    </div>
    <!--店舗一覧 -->
    <div class="col-md-8">
      <div class="shops-wrapper">
        <div class="page-header">
          <h1>店舗一覧</h1>
        </div>
        <div class="row">
          <%= render @shops %>
        </div>
        <div class="pagination pagination-centered">
          <%= paginate @shops %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/_sign_out.html.erb
<div class="jumbotron">
  <div class="top-wrapper">
    <div class="container">
      <h1>素敵な古着屋を見つけよう。</h1>
      <p>RopaRopaは古着屋の情報サイトです。<br>あなたも気になるお店を見つけてみませんか?</p>
      <%= link_to "新規登録(無料)", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</div>
<div class="landing-section gray-color">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <div class="landing-description">
          <i class="fa fa-search" aria-hidden="true"></i>
          <h2>検索</h2>
          <p>全国の古着屋を検索できます。<br>古着屋は順次追加中です。</p>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="landing-description">
          <i class="fa fa-heart" aria-hidden="true"></i>
          <h2>お気に入り</h2>
          <p>お店にいいね！ができます。<br>気になるお店をいいね！してリストに追加しよう。</p>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="landing-description">
          <i class="fa fa-comment" aria-hidden="true"></i>
          <h2>口コミ</h2>
          <p>お店に口コミができます。<br>訪れたことのあるお店にコメントを書いてみよう。</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="landing-section">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8">
        <div class="landing-shops">
          <h2>最新の古着屋</h2>
          <div class="row">
            <%= render @shops %>
          </div>
        </div>
      </div>
      <div class="col-sm-12 col-md-4">
        <div class="landing-areas">
          <h2>人気のエリア</h2>
          <div class="area area1">
            <%= link_to ({:controller=>"shops",:action=>"index",:q=>{:area_id_eq=>'1'}}) do %>
            <div class="area-mask">
              <h3>原宿</h3>
            </div>
            <% end %>
          </div>
          <div class="area area2">
            <%= link_to ({:controller=>"shops",:action=>"index",:q=>{:area_id_eq=>'2'}}) do %>
            <div class="area-mask">
              <h3>下北沢</h3>
            </div>
            <% end %>
          </div>
          <div class="area area3">
            <%= link_to ({:controller=>"shops",:action=>"index",:q=>{:area_id_eq=>'3'}}) do %>
            <div class="area-mask">
              <h3>高円寺</h3>
            </div>
            <% end %>
          </div>
          <!-- アドセンス -->
          <%= render "shared/horizontal_ad" %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="more text-center">
        <%= link_to "すべてのお店を見る", shops_path, class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  </div>
</div>
<div class="landing-section gray-color">
  <div class="container">
    <h3>あなたも素敵な古着屋を見つけてみませんか？</h3>
    <div class="text-center">
      <%= link_to "登録する", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</div>

app/views/home/published.html.erb
<% @page_title = "店舗掲載" %>

<div class="published-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="published-pr">
          <h1>お店を掲載してみませんか? ：）</h1>
          <p class="published-description">
            RopaRopa(ロパロパ)は古着屋さんの情報サイトです。全国にたくさんある古着屋さんのデータベースを作るべく日々店舗の追加を行っています。<br>
            あなたも古着好きな人々に自分のお店をアピールするために店舗情報を掲載しませんか？
          </p>
        </div>
        <div class="published-faq">
          <h1>よくある質問</h1>
          <div class="question-wrapper">
            <div class="question">
              <p>Q. 店舗掲載料はいくらですか？</p>
            </div>
            <div class="answer">
              <p>A. 基本的にはかかりません。無料です。</p>
            </div>
          </div>
          <div class="question-wrapper">
            <div class="question">
              <p>Q. 店舗情報は何を送ればいいですか？</p>
            </div>
            <div class="answer">
              <p>A. 店舗名・店舗ジャンル・店舗画像(1枚)・店舗概要(300文字以内)・所在地・電話番号・営業時間・定休日・店舗サイトURL・・・<br>
                 以上の項目をご用意していただいて、<%= mail_to "info@ropa-ropa.com" %>までお送りください。</p>
            </div>
          </div>
          <div class="question-wrapper">
            <div class="question">
              <p>Q. 実店舗がないのですが掲載可能でしょうか？</p>
            </div>
            <div class="answer">
              <p>A. はい大丈夫です。実店舗・ネットショップ問わず掲載可能です。</p>
            </div>
          </div>
          <div class="question-wrapper">
            <div class="question">
              <p>Q. 個人でも掲載できますか？</p>
            </div>
            <div class="answer">
              <p>A. もちろんです。法人・個人問わず掲載できます。</p>
            </div>
          </div>
          <div class="question-wrapper">
            <div class="question">
              <p>Q. 上記をみてもわからないことがある。</p>
            </div>
            <div class="answer">
              <p>A. わからないことや質問などは<%= link_to "こちらから", contact_path %>お気軽にお問い合わせください。</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/top.html.erb
<% @page_title = "RopaRopa" %>

<!-- ログインしている場合 -->
<% if user_signed_in? %>
  <%= render "sign_in" %>
<!-- ログインしていない場合 -->
<% else %>
  <%= render "sign_out" %>
<% end %>